version: "3"

services:
  database:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "flexiflex"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    image: mysql:5.7.21
    ports:
      - 3306:3306
